import java.util.Random;

public class GameData {

	int gameCategory;
	
	private String[] words;
	
	private int lastWordIndex = 0;
	private int currentLevel = 1;
	
	private boolean gameFinished = false;
	
	//total 10 words for country
	private String[] countryWords = {"INDIA","AMERICA","AFRICA","EUROPE","CHINA","JAPAN","KOREA","NEPAL","PERU","CANADA"}; 
	
	//for 11 animals
	private String[] animalWords = {"PIG","LION","TIGER","FROG","BEAR","CAT","CAMEL","DOG","ANT","COW","RAT"};
	
	private String[] occupationWords = {"SOFTWARE","HARDWARE","TEACHER","PLUMBER","POLICE","DOCTOR","CLERK","WATCHMAN","MANAGER","DEVELOPER"};
	
	//constructor taking category 
	public GameData(int category) {
		this.gameCategory = category;
		currentLevel = 1;
		loadWords();
	}
	
	//to give catergory
	 private void loadWords() {
		if(gameCategory == 1) {
			words = countryWords;
		}
		else if(gameCategory == 2) {
			words = animalWords;
		}
		else if(gameCategory == 3) {
			words = occupationWords;
		}
	}
	 
	 public int getCurrentLevel() {
		 return currentLevel;
	 }
	 
	 public void setCurrentLevel(int level) {
		 this.currentLevel = level;
	 }
	 
	 public void setGameFinished(boolean finished) {
		 //if you want to set whether game is true or not then we call setter
		 this.gameFinished = finished;
	 }
	 
	 public boolean getGameFinished() {
		return this.gameFinished;
	 }
	
	public int getLastWordIndex() {
		return lastWordIndex;
	}
	
	public String getWord() {
		lastWordIndex = new Random().nextInt(words.length);
		//here taking the word generated by the random index
	    return this.words[lastWordIndex];
	}
	
}
